name: openapi ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: ${{ github.repository }}-python-flask

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run gen:python-flask
      - run: docker build . --tag ${{ env.IMAGE_NAME }}:${{ github.sha }}
        working-directory: generator/python-flask
      - uses: sysdiglabs/benchmark-dockerfile@v1.0.0
        id: benchmark_dockerfile
        with:
          # CIS 4.3 Ensure that unnecessary packages are not installed in the container (Not Scored)
          disallowedPackages: "httpd, apt"
          # CIS 4.2 Ensure that containers use only trusted base images (Not Scored)
          trustedBaseImages: "httpd, alpine"
          # CIS 4.10 Ensure secrets are not stored in Dockerfiles (Not Scored)
          secretPatterns: "secret*"
      - run: echo '${{ steps.benchmark_dockerfile.outputs.violation_report }}' | jq '.cis_docker_benchmark_violation_report'
      - uses: aquasecurity/trivy-action@0.2.0
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"
