name: openapi ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap:
    runs-on: ubuntu-latest
    services:
      mock-api:
        image: stoplight/prism
        ports:
          - 4010:4010
        volumes:
          - ./api/petstore.swagger.yml:/docs/api.yaml:ro
        options: --entrypoint "mock -h 0.0.0.0 /docs/api.yaml --cors=false"
    steps:
      - uses: actions/checkout@v2
      - uses: zaproxy/action-api-scan@v0.1.0
        continue-on-error: true
        with:
          target: ./api/petstore.swagger.yml
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: report
          path: report_*
