name: openapi ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zab:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker run -dit --rm \
          -v $(pwd)/api/petstore.swagger.yml:/docs/api.yaml:ro \
          -p 4010:4010 \
          stoplight/prism \
          mock -h 0.0.0.0 /docs/api.yaml --cors=false
    - uses: zaproxy/action-api-scan@v0.1.0
      with:
        target: http://172.17.0.2:4010
        cmd_options: -t ./api/petstore.swagger.yml -r scan-result.html
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: report
        path: scan-result.html
